In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# librerías enfocadas en Machine-Learning
import sklearn
from sklearn.metrics.pairwise import polynomial_kernel

# Lineal

In [2]:
import numpy as np

# Matriz X
x = np.array([
    [1, 2, 3, 4, 5],
    [2, 4, 6, 8, 10],
    [3, 6, 9, 12, 15],
    [4, 8, 12, 16, 20]
])

# Vector Y
y = np.array([10, 20, 30, 40])


## Generación de kernel

In [3]:
k_pol = sklearn.metrics.pairwise.polynomial_kernel(x, Y=None, degree=1, gamma=1, coef0=0)


In [4]:
k_pol

array([[ 55., 110., 165., 220.],
       [110., 220., 330., 440.],
       [165., 330., 495., 660.],
       [220., 440., 660., 880.]])

In [5]:
gamma_r = 0.5

In [6]:
np.fill_diagonal(k_pol, k_pol.diagonal() + (1/gamma_r))

kernel = pd.DataFrame(k_pol)
kernel['1v'] = 1
kernel.loc[len(kernel)] = [1] * (kernel.shape[1])
kernel.at[4, '1v'] = 0
kernel

0      1      2      3  1v
0   57.0  110.0  165.0  220.0   1
1  110.0  222.0  330.0  440.0   1
2  165.0  330.0  497.0  660.0   1
3  220.0  440.0  660.0  882.0   1
4    1.0    1.0    1.0    1.0   0

In [7]:
finalY = np.hstack([y, np.array([0])])
y_col = finalY.reshape(-1, 1)
y_col

array([[10],
       [20],
       [30],
       [40],
       [ 0]])

In [8]:
y_col

array([[10],
       [20],
       [30],
       [40],
       [ 0]])

## Sistema de ecuaciones

In [9]:
sol = np.linalg.solve(kernel, y_col)
sol

array([[-0.05415162],
       [-0.01805054],
       [ 0.01805054],
       [ 0.05415162],
       [ 0.18050542]])

## Cálculo de $\alpha$  y $b$

In [10]:
alphas = sol[:-1]
b = sol[-1]
alphas, b

(array([[-0.05415162],
        [-0.01805054],
        [ 0.01805054],
        [ 0.05415162]]),
 array([0.18050542]))

## Predicción

In [11]:
nuevo = np.array([5, 10, 15, 20 ,25])

In [12]:
nuevo_r = nuevo.reshape(1, -1)

In [13]:
nuevo_pred = sklearn.metrics.pairwise.polynomial_kernel(x, Y=nuevo_r, degree=1, gamma=1, coef0=0)


In [14]:
nuevo_res = np.dot(alphas.T, nuevo_pred) + b
nuevo_res

array([[49.81949458]])

# Polinomial

## Generación de kernel

In [15]:
k_pol = sklearn.metrics.pairwise.polynomial_kernel(x, Y=None, degree=5, gamma=1, coef0=1)


In [16]:
k_pol

array([[5.50731776e+08, 1.68505816e+10, 1.26049301e+11, 5.27182965e+11],
       [1.68505816e+10, 5.27182965e+11, 3.97319581e+12, 1.66798810e+13],
       [1.26049301e+11, 3.97319581e+12, 3.00198406e+13, 1.26184874e+14],
       [5.27182965e+11, 1.66798810e+13, 1.26184874e+14, 5.30737216e+14]])

In [17]:
gamma_r = 7

In [18]:
np.fill_diagonal(k_pol, k_pol.diagonal() + (1/gamma_r))

kernel = pd.DataFrame(k_pol)
kernel['1v'] = 1
kernel.loc[len(kernel)] = [1] * (kernel.shape[1])
kernel.at[4, '1v'] = 0
kernel

0             1             2             3  1v
0  5.507318e+08  1.685058e+10  1.260493e+11  5.271830e+11   1
1  1.685058e+10  5.271830e+11  3.973196e+12  1.667988e+13   1
2  1.260493e+11  3.973196e+12  3.001984e+13  1.261849e+14   1
3  5.271830e+11  1.667988e+13  1.261849e+14  5.307372e+14   1
4  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   0

In [19]:
finalY = np.hstack([y, np.array([0])])
y_col = finalY.reshape(-1, 1)
y_col

array([[10],
       [20],
       [30],
       [40],
       [ 0]])

## Ecuación lineal

In [20]:
sol = np.linalg.solve(kernel, y_col)
sol

array([[-1.81043688e-06],
       [ 2.63545268e-06],
       [-9.76046802e-07],
       [ 1.51030995e-07],
       [ 7.20388265e+00]])

## Cálculo de $\alpha$ y $b$

In [21]:
alphas = sol[:-1]
b = sol[-1]
alphas, b

(array([[-1.81043688e-06],
        [ 2.63545268e-06],
        [-9.76046802e-07],
        [ 1.51030995e-07]]),
 array([7.20388265]))

## Predicción

In [22]:
nuevo = np.array([5, 10, 15, 20 ,25])

In [23]:
nuevo_r = nuevo.reshape(1, -1)

In [24]:
nuevo_pred = sklearn.metrics.pairwise.polynomial_kernel(x, Y=nuevo_r, degree=5, gamma=1, coef0=1)


In [25]:
nuevo_res = np.dot(alphas.T, nuevo_pred) + b
nuevo_res

array([[82.2458712]])

# Gaussiano

## Generación de kernel

In [26]:
k_rbf = sklearn.metrics.pairwise.rbf_kernel(x, Y=None, gamma=0.01)

In [27]:
k_rbf

array([[1.        , 0.57694981, 0.11080316, 0.00708341],
       [0.57694981, 1.        , 0.57694981, 0.11080316],
       [0.11080316, 0.57694981, 1.        , 0.57694981],
       [0.00708341, 0.11080316, 0.57694981, 1.        ]])

In [28]:
gamma_r = 1

In [29]:
np.fill_diagonal(k_rbf, k_rbf.diagonal() + (1/gamma_r))

kernel_rbf = pd.DataFrame(k_rbf)
kernel_rbf['1v'] = 1
kernel_rbf.loc[len(kernel_rbf)] = [1] * (kernel_rbf.shape[1])
kernel_rbf.at[4, '1v'] = 0
kernel_rbf

0         1         2         3  1v
0  2.000000  0.576950  0.110803  0.007083   1
1  0.576950  2.000000  0.576950  0.110803   1
2  0.110803  0.576950  2.000000  0.576950   1
3  0.007083  0.110803  0.576950  2.000000   1
4  1.000000  1.000000  1.000000  1.000000   0

## Ecuación lineal

In [30]:
sol = np.linalg.solve(kernel_rbf, y_col)
sol

array([[-7.26116735],
       [-1.13504862],
       [ 1.13504862],
       [ 7.26116735],
       [25.        ]])

## Cálculo de $\alpha$ y $b$

In [31]:
alphas_rbf = sol[:-1]
b_rbf = sol[-1]
alphas_rbf, b_rbf

(array([[-7.26116735],
        [-1.13504862],
        [ 1.13504862],
        [ 7.26116735]]),
 array([25.]))

## Predicción

In [32]:
nuevo_pred_rbf = sklearn.metrics.pairwise.rbf_kernel(x, Y=nuevo_r, gamma=0.01)

In [33]:
nuevo_res_rbf = np.dot(alphas_rbf.T, nuevo_pred_rbf) + b_rbf
nuevo_res_rbf

array([[29.30596159]])