In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf
from scipy.optimize import minimize


## EJERCICIO EXAMEN 

In [62]:
import numpy as np
import pandas as pd

# Matriz X
X = np.array([
    [1, 1.500, 3, 20],
    [1, 1.800, 4, 15],
    [1, 2.400, 4, 10],
    [1, 3.000, 5, 5],
    [1, 1.300, 2, 25],
    [1, 2.000, 3, 18],
    [1, 2.200, 4, 12],
    [1, 1.600, 3, 22],
    [1, 2.800, 5, 8],
    [1, 1.900, 4, 16]
])
X=pd.DataFrame(X)

In [63]:
# Vector Y
import numpy as np

Y = np.array([
    [300.000],
    [350.000],
    [500.000],
    [600.000],
    [250.000],
    [400.000],
    [450.000],
    [320.000],
    [580.000],
    [420.000]
])


In [64]:
matriz_transpuesta=X.T
XTX= np.dot(matriz_transpuesta,X)
XTY= np.dot(matriz_transpuesta,Y)
XTXMENOS1= np.linalg.inv(XTX)
B=  np.dot(XTXMENOS1,XTY)
B

array([[-85.15078083],
       [202.46701669],
       [ 16.79052235],
       [  1.65354066]])

In [65]:
import numpy as np

# Matriz de características para la predicción (nuevas observaciones)
X_prediccion = np.array([
    [1, 2.000, 3, 20],  # Ejemplo 1
    [1, 2.500, 4, 10]   # Ejemplo 2
])

# Calcula las predicciones
Y_prediccion = np.dot(X_prediccion, B)

print("Predicciones:")
print(Y_prediccion)


Predicciones:
[[403.22563274]
 [504.71425687]]


In [66]:
Y_pred = np.dot(X, B)

# Calcular el residuo: (Y - X B)
residuo = Y - Y_pred

# Calcular la varianza: 1/N * (residuo^T @ residuo)
N = Y.shape[0]  # Número de observaciones
varianza = (1 / N) * np.dot(residuo.T, residuo)

print("Varianza:", varianza)

Varianza: [[167.51783791]]


In [67]:
import numpy as np

# Constantes
pi = 3.14159265359


coeficiente = 1 / ((2 * pi * varianza) ** (N / 2))


exponente = -1 / (2 * varianza) * np.dot(residuo.T, residuo)
exponencial = np.exp(exponente)

# Límite final
L = coeficiente * exponencial

print("verosimilitud:", L)


verosimilitud: [[5.2158243e-18]]


In [68]:
import numpy as np

# Valores proporcionados
betas = np.array([
    [1.64335541e+08],
    [-4.30189661e+04],
    [-3.63751660e+06],
    [-4.12389730e+06]
])

# Definir lambda
_lambda = 1  # Puedes ajustar este valor

# Número de betas
n = betas.shape[0]

# Calcular la sumatoria de los cuadrados de las betas
sumatoria_betas_cuadrado = np.sum(betas**2)

# Término de la fracción: (\lambda^n) / (\sqrt{2\pi}^n)
coeficiente = (_lambda**n) / ((np.sqrt(2 * pi))**n)

# Término exponencial: exp(-1 / (2 * lambda^2) * sumatoria_betas_cuadrado)
exponente = -1 / (2 * (_lambda**2)) * sumatoria_betas_cuadrado
exponencial = np.exp(exponente)

# Resultado final
P = coeficiente * exponencial

print("Resultado de P:", P)


Resultado de P: 0.0


In [69]:
def add_lambda_to_diagonal(matrix, lambda_value):
    # Sumar lambda a la diagonal de la matriz
    return matrix + np.eye(matrix.shape[0]) * lambda_value

# Ejemplo de uso
lambda_value = 1
XTX_lambda = add_lambda_to_diagonal(XTX, lambda_value)
XTX_lambda

array([[  11.  ,   20.5 ,   37.  ,  151.  ],
       [  20.5 ,   45.79,   80.1 ,  278.9 ],
       [  37.  ,   80.1 ,  146.  ,  507.  ],
       [ 151.  ,  278.9 ,  507.  , 2648.  ]])

In [70]:
XTXMENOS1_lambda= np.linalg.inv(XTX_lambda)
B_lambda=  np.dot(XTXMENOS1_lambda,XTY)
B_lambda

array([[18.33704999],
       [87.4427385 ],
       [62.11562692],
       [-0.81166811]])

In [71]:
X_prediccion = np.array([
    [1, 2.000, 3, 20],  # Ejemplo 1
    [1, 2.500, 4, 10]   # Ejemplo 2
])

# Calcula las predicciones
Y_prediccion1 = np.dot(X_prediccion, B_lambda)

print("Predicciones:")
print(Y_prediccion1)

Predicciones:
[[363.33604548]
 [477.28972277]]


In [72]:
Y_pred1 = np.dot(X, B_lambda)

# Calcular el residuo: (Y - X B)
residuo1 = Y - Y_pred1



# Calcular la varianza: 1/N * (residuo^T @ residuo)
N = Y.shape[0]  # Número de observaciones
varianza1 = (1 / N) * np.dot(residuo1.T, residuo1)

print("Varianza:", varianza1)

Varianza: [[701.81565141]]


In [73]:
import numpy as np

# Constantes
pi = 3.14159265359


coeficiente1 = 1 / ((2 * pi * varianza1) ** (N / 2))


exponente1 = -1 / (2 * varianza1) * np.dot(residuo1.T, residuo1)
exponencial1 = np.exp(exponente1)

# Límite final
L1 = coeficiente1 * exponencial1

print("verosimilitud:", L1)

verosimilitud: [[4.04122473e-21]]
