In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# librerías enfocadas en Machine-Learning
import sklearn
from sklearn.metrics.pairwise import polynomial_kernel

# Lineal

In [2]:
import numpy as np

# Matriz X
x = np.array([
    [1, 2, 3, 4, 5],
    [2, 4, 6, 8, 10],
    [3, 6, 9, 12, 15],
    [4, 8, 12, 16, 20]
])

# Vector Y
y = np.array([10, 20, 30, 40])


## Generación de kernel

In [3]:
k_pol = sklearn.metrics.pairwise.polynomial_kernel(x, Y=None, degree=1, gamma=1, coef0=0)


In [4]:
k_pol

array([[ 55., 110., 165., 220.],
       [110., 220., 330., 440.],
       [165., 330., 495., 660.],
       [220., 440., 660., 880.]])

In [5]:
gamma_r = 0.5

In [6]:
np.fill_diagonal(k_pol, k_pol.diagonal() + (1/gamma_r))

kernel = pd.DataFrame(k_pol)
kernel['1v'] = 1
kernel.loc[len(kernel)] = [1] * (kernel.shape[1])
kernel.at[4, '1v'] = 0
kernel

0      1      2      3  1v
0   57.0  110.0  165.0  220.0   1
1  110.0  222.0  330.0  440.0   1
2  165.0  330.0  497.0  660.0   1
3  220.0  440.0  660.0  882.0   1
4    1.0    1.0    1.0    1.0   0

In [7]:
finalY = np.hstack([y, np.array([0])])
y_col = finalY.reshape(-1, 1)
y_col

array([[10],
       [20],
       [30],
       [40],
       [ 0]])

In [8]:
y_col

array([[10],
       [20],
       [30],
       [40],
       [ 0]])

## Sistema de ecuaciones

In [9]:
sol = np.linalg.solve(kernel, y_col)
sol

array([[-0.05415162],
       [-0.01805054],
       [ 0.01805054],
       [ 0.05415162],
       [ 0.18050542]])

## Cálculo de $\alpha$  y $b$

In [10]:
alphas = sol[:-1]
b = sol[-1]
alphas, b

(array([[-0.05415162],
        [-0.01805054],
        [ 0.01805054],
        [ 0.05415162]]),
 array([0.18050542]))

## Predicción

In [11]:
nuevo = np.array([5, 10, 15, 20 ,25])

In [12]:
nuevo_r = nuevo.reshape(1, -1)

In [13]:
nuevo_pred = sklearn.metrics.pairwise.polynomial_kernel(x, Y=nuevo_r, degree=1, gamma=1, coef0=0)


In [14]:
nuevo_res = np.dot(alphas.T, nuevo_pred) + b
nuevo_res

array([[49.81949458]])

# Polinomial

## Generación de kernel

In [15]:
k_pol = sklearn.metrics.pairwise.polynomial_kernel(x, Y=None, degree=3, gamma=1, coef0=1)


In [16]:
k_pol

array([[1.75616000e+05, 1.36763100e+06, 4.57429600e+06, 1.07938610e+07],
       [1.36763100e+06, 1.07938610e+07, 3.62646910e+07, 8.57661210e+07],
       [4.57429600e+06, 3.62646910e+07, 1.22023936e+08, 2.88804781e+08],
       [1.07938610e+07, 8.57661210e+07, 2.88804781e+08, 6.83797841e+08]])

In [17]:
gamma_r = 1

In [18]:
np.fill_diagonal(k_pol, k_pol.diagonal() + (1/gamma_r))

kernel = pd.DataFrame(k_pol)
kernel['1v'] = 1
kernel.loc[len(kernel)] = [1] * (kernel.shape[1])
kernel.at[4, '1v'] = 0
kernel

0           1            2            3  1v
0    175617.0   1367631.0    4574296.0   10793861.0   1
1   1367631.0  10793862.0   36264691.0   85766121.0   1
2   4574296.0  36264691.0  122023937.0  288804781.0   1
3  10793861.0  85766121.0  288804781.0  683797842.0   1
4         1.0         1.0          1.0          1.0   0

In [19]:
finalY = np.hstack([y, np.array([0])])
y_col = finalY.reshape(-1, 1)
y_col

array([[10],
       [20],
       [30],
       [40],
       [ 0]])

## Ecuación lineal

In [20]:
sol = np.linalg.solve(kernel, y_col)
sol

array([[-0.1326323 ],
       [ 0.29060073],
       [-0.21399471],
       [ 0.05602628],
       [ 3.18613872]])

## Cálculo de $\alpha$ y $b$

In [21]:
alphas = sol[:-1]
b = sol[-1]
alphas, b

(array([[-0.1326323 ],
        [ 0.29060073],
        [-0.21399471],
        [ 0.05602628]]),
 array([3.18613872]))

## Predicción

In [22]:
nuevo = np.array([5, 10, 15, 20 ,25])

In [23]:
nuevo_r = nuevo.reshape(1, -1)

In [24]:
nuevo_pred = sklearn.metrics.pairwise.polynomial_kernel(x, Y=nuevo_r, degree=3, gamma=1, coef0=1)


In [25]:
nuevo_res = np.dot(alphas.T, nuevo_pred) + b
nuevo_res

array([[47.19689137]])

# Gaussiano

## Generación de kernel

In [34]:
k_rbf = sklearn.metrics.pairwise.rbf_kernel(x, Y=None, gamma=0.01)

In [35]:
k_rbf

array([[1.        , 0.57694981, 0.11080316, 0.00708341],
       [0.57694981, 1.        , 0.57694981, 0.11080316],
       [0.11080316, 0.57694981, 1.        , 0.57694981],
       [0.00708341, 0.11080316, 0.57694981, 1.        ]])

In [27]:
gamma_r = 1

In [28]:
np.fill_diagonal(k_rbf, k_rbf.diagonal() + (1/gamma_r))

kernel_rbf = pd.DataFrame(k_rbf)
kernel_rbf['1v'] = 1
kernel_rbf.loc[len(kernel_rbf)] = [1] * (kernel_rbf.shape[1])
kernel_rbf.at[4, '1v'] = 0
kernel_rbf

0         1         2         3  1v
0  2.000000  0.576950  0.110803  0.007083   1
1  0.576950  2.000000  0.576950  0.110803   1
2  0.110803  0.576950  2.000000  0.576950   1
3  0.007083  0.110803  0.576950  2.000000   1
4  1.000000  1.000000  1.000000  1.000000   0

## Ecuación lineal

In [29]:
sol = np.linalg.solve(kernel_rbf, y_col)
sol

array([[-7.26116735],
       [-1.13504862],
       [ 1.13504862],
       [ 7.26116735],
       [25.        ]])

## Cálculo de $\alpha$ y $b$

In [30]:
alphas_rbf = sol[:-1]
b_rbf = sol[-1]
alphas_rbf, b_rbf

(array([[-7.26116735],
        [-1.13504862],
        [ 1.13504862],
        [ 7.26116735]]),
 array([25.]))

## Predicción

In [31]:
nuevo_pred_rbf = sklearn.metrics.pairwise.rbf_kernel(x, Y=nuevo_r, gamma=0.01)

In [32]:
nuevo_res_rbf = np.dot(alphas_rbf.T, nuevo_pred_rbf) + b_rbf
nuevo_res_rbf

array([[29.30596159]])