In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# librerías enfocadas en Machine-Learning
import sklearn
from sklearn.metrics.pairwise import polynomial_kernel

# Lineal

In [68]:
import numpy as np

# Matriz X
x = np.array([
    [1, 2, 3, 4, 5],
    [2, 4, 6, 8, 10],
    [3, 6, 9, 12, 15],
    [4, 8, 12, 16, 20]
])

# Vector Y
y = np.array([10, 20, 30, 40])


## Generación de kernel

In [69]:
k_pol = sklearn.metrics.pairwise.polynomial_kernel(x, Y=None, degree=1, gamma=1, coef0=0)


In [70]:
k_pol

array([[ 55., 110., 165., 220.],
       [110., 220., 330., 440.],
       [165., 330., 495., 660.],
       [220., 440., 660., 880.]])

In [71]:
gamma_r = 0.5

In [72]:
np.fill_diagonal(k_pol, k_pol.diagonal() + (1/gamma_r))

kernel = pd.DataFrame(k_pol)
kernel['1v'] = 1
kernel.loc[len(kernel)] = [1] * (kernel.shape[1])
kernel.at[4, '1v'] = 0
kernel

0      1      2      3  1v
0   57.0  110.0  165.0  220.0   1
1  110.0  222.0  330.0  440.0   1
2  165.0  330.0  497.0  660.0   1
3  220.0  440.0  660.0  882.0   1
4    1.0    1.0    1.0    1.0   0

In [73]:
finalY = np.hstack([y, np.array([0])])
y_col = finalY.reshape(-1, 1)
y_col

array([[10],
       [20],
       [30],
       [40],
       [ 0]])

In [74]:
y_col

array([[10],
       [20],
       [30],
       [40],
       [ 0]])

## Sistema de ecuaciones

In [75]:
sol = np.linalg.solve(kernel, y_col)
sol

array([[-0.05415162],
       [-0.01805054],
       [ 0.01805054],
       [ 0.05415162],
       [ 0.18050542]])

## Cálculo de $\alpha$  y $b$

In [76]:
alphas = sol[:-1]
b = sol[-1]
alphas, b

(array([[-0.05415162],
        [-0.01805054],
        [ 0.01805054],
        [ 0.05415162]]),
 array([0.18050542]))

## Predicción

In [77]:
nuevo = np.array([5, 10, 15, 20 ,25])

In [78]:
nuevo_r = nuevo.reshape(1, -1)

In [79]:
nuevo_pred = sklearn.metrics.pairwise.polynomial_kernel(x, Y=nuevo_r, degree=1, gamma=1, coef0=0)


In [80]:
nuevo_res = np.dot(alphas.T, nuevo_pred) + b
nuevo_res

array([[49.81949458]])

# Polinomial

## Generación de kernel

In [81]:
k_pol = sklearn.metrics.pairwise.polynomial_kernel(x, Y=None, degree=4, gamma=1, coef0=1)


In [82]:
k_pol

array([[9.83449600e+06, 1.51807041e+08, 7.59333136e+08, 2.38544328e+09],
       [1.51807041e+08, 2.38544328e+09, 1.20036127e+10, 3.78228594e+10],
       [7.59333136e+08, 1.20036127e+10, 6.05238723e+10, 1.90899960e+11],
       [2.38544328e+09, 3.78228594e+10, 1.90899960e+11, 6.02425898e+11]])

In [83]:
gamma_r = 2

In [84]:
np.fill_diagonal(k_pol, k_pol.diagonal() + (1/gamma_r))

kernel = pd.DataFrame(k_pol)
kernel['1v'] = 1
kernel.loc[len(kernel)] = [1] * (kernel.shape[1])
kernel.at[4, '1v'] = 0
kernel

0             1             2             3  1v
0  9.834496e+06  1.518070e+08  7.593331e+08  2.385443e+09   1
1  1.518070e+08  2.385443e+09  1.200361e+10  3.782286e+10   1
2  7.593331e+08  1.200361e+10  6.052387e+10  1.909000e+11   1
3  2.385443e+09  3.782286e+10  1.909000e+11  6.024259e+11   1
4  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   0

In [85]:
finalY = np.hstack([y, np.array([0])])
y_col = finalY.reshape(-1, 1)
y_col

array([[10],
       [20],
       [30],
       [40],
       [ 0]])

## Ecuación lineal

In [86]:
sol = np.linalg.solve(kernel, y_col)
sol

array([[-5.89776291e-04],
       [ 1.01985609e-03],
       [-5.39271600e-04],
       [ 1.09191797e-04],
       [ 4.77308500e+00]])

## Cálculo de $\alpha$ y $b$

In [87]:
alphas = sol[:-1]
b = sol[-1]
alphas, b

(array([[-0.00058978],
        [ 0.00101986],
        [-0.00053927],
        [ 0.00010919]]),
 array([4.773085]))

## Predicción

In [88]:
nuevo = np.array([5, 10, 15, 20 ,25])

In [89]:
nuevo_r = nuevo.reshape(1, -1)

In [90]:
nuevo_pred = sklearn.metrics.pairwise.polynomial_kernel(x, Y=nuevo_r, degree=4, gamma=1, coef0=1)


In [91]:
nuevo_res = np.dot(alphas.T, nuevo_pred) + b
nuevo_res

array([[54.76354199]])

# Gaussiano

## Generación de kernel

In [92]:
k_rbf = sklearn.metrics.pairwise.rbf_kernel(x, Y=None, gamma=0.01)

In [93]:
k_rbf

array([[1.        , 0.57694981, 0.11080316, 0.00708341],
       [0.57694981, 1.        , 0.57694981, 0.11080316],
       [0.11080316, 0.57694981, 1.        , 0.57694981],
       [0.00708341, 0.11080316, 0.57694981, 1.        ]])

In [94]:
gamma_r = 1

In [95]:
np.fill_diagonal(k_rbf, k_rbf.diagonal() + (1/gamma_r))

kernel_rbf = pd.DataFrame(k_rbf)
kernel_rbf['1v'] = 1
kernel_rbf.loc[len(kernel_rbf)] = [1] * (kernel_rbf.shape[1])
kernel_rbf.at[4, '1v'] = 0
kernel_rbf

0         1         2         3  1v
0  2.000000  0.576950  0.110803  0.007083   1
1  0.576950  2.000000  0.576950  0.110803   1
2  0.110803  0.576950  2.000000  0.576950   1
3  0.007083  0.110803  0.576950  2.000000   1
4  1.000000  1.000000  1.000000  1.000000   0

## Ecuación lineal

In [96]:
sol = np.linalg.solve(kernel_rbf, y_col)
sol

array([[-7.26116735],
       [-1.13504862],
       [ 1.13504862],
       [ 7.26116735],
       [25.        ]])

## Cálculo de $\alpha$ y $b$

In [97]:
alphas_rbf = sol[:-1]
b_rbf = sol[-1]
alphas_rbf, b_rbf

(array([[-7.26116735],
        [-1.13504862],
        [ 1.13504862],
        [ 7.26116735]]),
 array([25.]))

## Predicción

In [98]:
nuevo_pred_rbf = sklearn.metrics.pairwise.rbf_kernel(x, Y=nuevo_r, gamma=0.01)

In [99]:
nuevo_res_rbf = np.dot(alphas_rbf.T, nuevo_pred_rbf) + b_rbf
nuevo_res_rbf

array([[29.30596159]])