In [1]:
import numpy as np
import pandas as pd

## Datos

In [2]:
X = np.array([
    [2, 5, 2, 4],
    [3.20, 6, 3, 4],
    [1.50, 3, 2, 2],
    [0.80, 2, 0, 1],
    [4, 3, 3, 4],
])

y = np.array([
    3.5,
    4.7,
    2.4,
    1.5,
    6.0,
    0  # Valor agregado para que coincida con el tamaño de K_df
])

## Matriz Kernel

\begin{bmatrix}
K + \frac{1}{gamma}I & 1 \\
1^T & 0 \\
\end{bmatrix}

Esto multiplicado por 

\begin{bmatrix}
\alpha \\
b \\
\end{bmatrix}

Es igual a 
\begin{bmatrix}
Y \\
0 \\
\end{bmatrix}

Se multiplica casa por casa, analiza cuanto se parecen, mientras más alto más se parecen las casas.

In [3]:
# Calcular K y modificar la diagonal
gamma = 1
K = np.dot(X, X.T)
np.fill_diagonal(K, K.diagonal() + (1/gamma))

# Convertir K en DataFrame y agregar fila y columna de unos
K_df = pd.DataFrame(K)
K_df['ones'] = 1
K_df.loc[len(K_df)] = [1] * (K_df.shape[1])
K_df.at[5, 'ones'] = 0  # Ajuste en la posición correcta
K_df

0      1      2      3     4  ones
0  50.0  58.40  30.00  15.60  45.0     1
1  58.4  72.24  36.80  18.56  55.8     1
2  30.0  36.80  20.25   9.20  29.0     1
3  15.6  18.56   9.20   6.64  13.2     1
4  45.0  55.80  29.00  13.20  51.0     1
5   1.0   1.00   1.00   1.00   1.0     0

In [4]:
sol = np.linalg.solve(K_df, y)
sol

array([-0.12978214,  0.06053108, -0.30878595,  0.06768309,  0.31035393,
        0.69588783])

In [5]:
alphas = sol[:-1]
b = sol[-1]
alphas, b

(array([-0.12978214,  0.06053108, -0.30878595,  0.06768309,  0.31035393]),
 0.6958878293317244)

In [6]:
# Nueva casa
x_new = np.array([2.50, 5, 3, 3])

$\hat y = w^T X + b$

In [7]:
# vector w para el modelo
w = np.dot(alphas, X)

# calculo del precio de la nueva casa (predicción)
y_hat = np.dot(w, x_new) + b

y_hat

3.8340375409897844

## Kernel polinomial

In [8]:
## Kernel polinomial
K = np.dot(X, X.T)
K_df_lineal = pd.DataFrame(K)
K_df_lineal

K_pol = K_df_lineal + 1
K_pol = K_pol ** 2
K_pol

0          1          2         3        4
0  2500.00  3528.3600   961.0000  275.5600  2116.00
1  3528.36  5218.6176  1428.8400  382.5936  3226.24
2   961.00  1428.8400   410.0625  104.0400   900.00
3   275.56   382.5936   104.0400   44.0896   201.64
4  2116.00  3226.2400   900.0000  201.6400  2601.00

In [9]:
K_pol = np.array(K_pol)
np.fill_diagonal(K_pol, K_pol.diagonal() + (1/gamma))

K_pol = pd.DataFrame(K_pol)
# Convertir K en DataFrame y agregar fila y columna de unos
K_pol['ones'] = 1
K_pol.loc[len(K_pol)] = [1] * (K_pol.shape[1])
K_pol.at[5, 'ones'] = 0  # Ajuste en la posición correcta
K_pol

0          1          2         3        4  ones
0  2501.00  3528.3600   961.0000  275.5600  2116.00     1
1  3528.36  5219.6176  1428.8400  382.5936  3226.24     1
2   961.00  1428.8400   411.0625  104.0400   900.00     1
3   275.56   382.5936   104.0400   45.0896   201.64     1
4  2116.00  3226.2400   900.0000  201.6400  2602.00     1
5     1.00     1.0000     1.0000    1.0000     1.00     0

In [10]:
sol_pol = np.linalg.solve(K_pol, y)
sol_pol

array([ 1.59632399e-03, -2.89066848e-03,  3.65021182e-04, -3.23594646e-03,
        4.16526977e-03,  1.43411395e+00])

In [11]:
alphas_pol = sol_pol[:-1]
b_pol = sol_pol[-1]
alphas_pol, b_pol

(array([ 0.00159632, -0.00289067,  0.00036502, -0.00323595,  0.00416527]),
 1.4341139522388606)

In [12]:
# Nueva casa
x_new = np.array([2.50, 5, 3, 3])

In [13]:
w_values = []

for i in range (len(X)):
    valor = (np.dot(X[i], x_new) + 1) ** 2 * (alphas_pol[i])
    w_values.append(valor)

np.sum(w_values) + b_pol

3.601124121460885